### ISSUE TITLE
"rows per page" dropdown broken on Data tab of request page

### ISSUE THREAD

**Issue by emannenicholas** [LCOGT/observation-portal-frontend#110]
The "rows per page" dropdown button on the Data tab of a request page only shows 10 as an option, and pressing the button does not bring up other options.  It would be nice if this dropdown were either removed, so no one is tempted to click on it, or other options were given like 20, 50, and 100.

![rows_per_page_bug](https://github.com/user-attachments/assets/a5b0d57c-9b4b-4001-ac6d-0e124cfefb13)

**Comment by jnation3406** [comment]
I would be tempted to just remove this as allowing lots of rows will make the UI worse and harder to navigate, and I would want to steer people to using the science archive UI in that case. But if its a simple fix I don't really mind either way.
